### PR TITLE
Allow redirections

### PR DESCRIPTION
**Pull request by duboism**
This PR addresses #33 by introducing an option to allow redirections (they can be disabled).

The implementation is rather simple but the PR is a bit large because we added some notes about options, cleaned some files, etc.

### CODE REVIEW

**Comment by duboism** [comment]
I converted the PR to draft and removed "[WIP]" from the title.

**Comment by duboism** [comment]
As discussed, we don't want to rely on `Biomajconfig.DEFAULTS` for initialization so 38c0bfe removes it.

**Comment by duboism** [comment]
Updated `CHANGES.txt` and removed draft status.

**Comment by duboism** [comment]
Just added some notes about the version in which some options were introduced.

**Comment by duboism** [comment]
Switched back to draft because I forgot to log information about redirections (which will allow better tests).

**Comment by osallou** [comment]
looks fine for me, ready for merge?

**Comment by duboism** [comment]
Ready for merge. Thanks in advance.

**Pull request merged**
