### PR TITLE
Speed up IRODDownload

### PR DESCRIPTION
**Pull request by duboism**
This PR introduces a new hook method `_network_configuration` which  is called  before network methods (`list` and `download`) to perform configuration (this generalizes `CurlDownload._basic_curl_configuration`).

This greatly speeds up the download of many files for IRODSDownloader (mainly because we don't cleanup and recreate the session after each download) and a bit for CurlDownloader (because less reconfiguration of the curl object).

### CODE REVIEW

**Comment by osallou** [comment]
Is it ready for merge?

**Comment by duboism** [comment]
I think it is (unit tests are green and I have made some functional tests). Maybe we should just check that microservice mode is not broken.

**Comment by osallou** [comment]
Renaming will not impact microservices.
Service or not, you get a handler and call list or download.
Internal logic afterward does not matter .

Only constraint as we previously discussed is to not depend on bank info or
property file directly (everything goes through message), which was already
the case.

**Comment by duboism** [comment]
OK, just wanted to be sure. The PR can be merged.

**Pull request merged**
